name: static-website
on:
  pull_request:
  push:
    branches:
      - main
      - test-cache
#  schedule:
#    - cron: "0 2 * * *"
env:
  ID_DOCKER: "wilfriedmambou237"
  IMAGE_NAME: "staticwebsite"
  IMAGE_TAG: "latest"
  APP_CONTAINER_PORT: "80"
  APP_EXPOSED_PORT: "80"

jobs:
  build:
    name: BUILD DOCKER IMAGE
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Build Image
        run: |
          docker build -t ${ID_DOCKER}/$IMAGE_NAME:$IMAGE_TAG .
          docker save ${ID_DOCKER}/$IMAGE_NAME:$IMAGE_TAG > $IMAGE_NAME
          echo "IMAGE_NAME=staticwebsite" >> $GITHUB_ENV

      - name: Cache artefact
        uses: actions/cache@v3
        with:
          key: image
          path: ${{ env.IMAGE_NAME }}

  run-and-test:
    name: RUN AND TEST CONTAINER
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace from job build
        uses: actions/cache@v3
        with:
          key: image
          path: ${{ env.IMAGE_NAME }}
      - name: Run container based on built image
        run: |
          docker load < $IMAGE_NAME
          docker run --name $IMAGE_NAME -d -p ${APP_EXPOSED_PORT}:${APP_CONTAINER_PORT} -e PORT=$APP_CONTAINER_PORT ${ID_DOCKER}/$IMAGE_NAME:$IMAGE_TAG
          sleep 5

      - name: Test image.
        run: curl http://172.17.0.1:${APP_EXPOSED_PORT} | grep -i "Dimension"

      - name: Clean Container
        run: |
          docker stop $IMAGE_NAME
          docker rm $IMAGE_NAME

  push:
    name: PUSH IMAGE ON DOCKERHUB
    needs: run-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace from job build
        uses: actions/cache@v3
        with:
          key: image
          path: ${{ env.IMAGE_NAME }}

      - name: Login and Push Image on docker hub
        run: |
          docker load < $IMAGE_NAME
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u $ID_DOCKER --password-stdin
          docker push ${ID_DOCKER}/$IMAGE_NAME:$IMAGE_TAG

  deploy:
    name: DEPLOY APPLICATION
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Install and configure Heroku CLI
        run: |
          sudo apt install nodejs
          echo "STAGING=${ID_DOCKER}-staging" >> $GITHUB_ENV
          echo "PRODUCTION=${ID_DOCKER}-production" >> $GITHUB_ENV

      - name: Heroku Login
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Create Staging App if not exists
        run: |
          heroku create ${STAGING} || true
          heroku stack:set container -a ${STAGING}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy Staging
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:push -a ${STAGING} web
          heroku container:release -a ${STAGING} web

      - name: Create PRODUCTION App if not exists
        run: |
          heroku create ${PRODUCTION} || true
          heroku stack:set container -a ${PRODUCTION}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy PRODUCTION
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:push -a ${PRODUCTION} web
          heroku container:release -a ${PRODUCTION} web
